# Generated by Django 5.1.1 on 2024-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1', 'Post-Trauma'), ('2', 'Post-Recovery'), ('3', 'Migraines'), ('4', 'Chronic Pains')], max_length=100)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
